//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPWA_Assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class juego
    {
        public int idjuego { get; set; }
        public string nomJuego { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> existencias { get; set; }
        public string imagen { get; set; }
        public Nullable<int> idcategoria { get; set; }
    
        public virtual categoria categoria { get; set; }
    }
}
